using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WpfStudyingSystem.Script.DatabaseScript.Interfaces;

namespace WpfStudyingSystem.Script.DatabaseScript.Usables
{
    public class DatabaseConnectionString : IDatabaseConnectionString
    {

        //This connection string is also written in app xaml (as i emember), so this script mostly lost its purpose
        //But its easyer, and safer, to experement with it, instead of autogenerated config, and
        //current controllers depend on it, so leave it as is

        private string databaseName = "StudySystemDB";
        public string DatabaseName { get => databaseName; set => databaseName = value; }
        public string ConnectionString => @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\" +databaseName+ @".mdf;Integrated Security=True";
    }
}
