//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfStudyingSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfStudyingSystem.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying system.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Crd_Failed {
            get {
                return ResourceManager.GetString("Crd_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Crd_Pass {
            get {
                return ResourceManager.GetString("Crd_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name is required..
        /// </summary>
        public static string Msg_CourseNameRequired {
            get {
                return ResourceManager.GetString("Msg_CourseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string Msg_NameRequired {
            get {
                return ResourceManager.GetString("Msg_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        public static string Msg_SaveFailed {
            get {
                return ResourceManager.GetString("Msg_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an assignment first..
        /// </summary>
        public static string Msg_SelectAssignmentFirst {
            get {
                return ResourceManager.GetString("Msg_SelectAssignmentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a course first..
        /// </summary>
        public static string Msg_SelectCourseFirst {
            get {
                return ResourceManager.GetString("Msg_SelectCourseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are not available..
        /// </summary>
        public static string Msg_ServicesNotAvailable {
            get {
                return ResourceManager.GetString("Msg_ServicesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher name is required..
        /// </summary>
        public static string Msg_TeacherNameRequired {
            get {
                return ResourceManager.GetString("Msg_TeacherNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Ui_Add {
            get {
                return ResourceManager.GetString("Ui_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create assignment.
        /// </summary>
        public static string Ui_Assignment_CreateTitle {
            get {
                return ResourceManager.GetString("Ui_Assignment_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact assignment.
        /// </summary>
        public static string Ui_Assignment_RedactTitle {
            get {
                return ResourceManager.GetString("Ui_Assignment_RedactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment info.
        /// </summary>
        public static string Ui_AssignmentInfo {
            get {
                return ResourceManager.GetString("Ui_AssignmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments list selectable.
        /// </summary>
        public static string UI_AssignmentsListSelectable {
            get {
                return ResourceManager.GetString("UI_AssignmentsListSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ui_Cancel {
            get {
                return ResourceManager.GetString("Ui_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create course.
        /// </summary>
        public static string Ui_Course_CreateTitle {
            get {
                return ResourceManager.GetString("Ui_Course_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact course.
        /// </summary>
        public static string Ui_Course_RedactTitle {
            get {
                return ResourceManager.GetString("Ui_Course_RedactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses selectable.
        /// </summary>
        public static string UI_CoursesSelectable {
            get {
                return ResourceManager.GetString("UI_CoursesSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Ui_Create {
            get {
                return ResourceManager.GetString("Ui_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Ui_Delete {
            get {
                return ResourceManager.GetString("Ui_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Ui_Description {
            get {
                return ResourceManager.GetString("Ui_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string Ui_DueDate {
            get {
                return ResourceManager.GetString("Ui_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Ui_Filter {
            get {
                return ResourceManager.GetString("Ui_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Ui_Import {
            get {
                return ResourceManager.GetString("Ui_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Ui_Name {
            get {
                return ResourceManager.GetString("Ui_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ui_Ok {
            get {
                return ResourceManager.GetString("Ui_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact.
        /// </summary>
        public static string Ui_Redact {
            get {
                return ResourceManager.GetString("Ui_Redact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student info.
        /// </summary>
        public static string Ui_StudentInfo {
            get {
                return ResourceManager.GetString("Ui_StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students list.
        /// </summary>
        public static string UI_StudentsList {
            get {
                return ResourceManager.GetString("UI_StudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher full name.
        /// </summary>
        public static string Ui_TeacherFullName {
            get {
                return ResourceManager.GetString("Ui_TeacherFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher name.
        /// </summary>
        public static string UI_TeacherName {
            get {
                return ResourceManager.GetString("UI_TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Ui_Type {
            get {
                return ResourceManager.GetString("Ui_Type", resourceCulture);
            }
        }
    }
}
